# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myapp_test

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          cd backend
          bundle install --jobs 4 --retry 3

      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          cd backend
          bundle exec rails db:create db:migrate
          bundle exec rspec

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          tags: myapp:${{ github.sha }}

  # deploy:
  #   needs: build

  #   environment:
  #     name: production
  #     url: ${{ secrets.PRODUCTION_URL }}

  #   steps:
  #     - name: Deploy to production
  #       uses: easingthemes/ssh-deploy@v2.2.0
  #       with:
  #         ssh_private_key: $
